### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by hyue0768** [M1kuW1ll/MMASim#2]
Hi! I run the runscript.py and return errors. Is there any solutions? Thanks
`Traceback (most recent call last):
  File "/home/os/yuehuang/MMASim/runscript.py", line 6, in <module>
    from main import Auction
  File "/home/os/yuehuang/MMASim/main.py", line 250, in <module>
    model.step()
  File "/home/os/yuehuang/MMASim/main.py", line 217, in step
    self.schedule.step()
  File "/home/os/.local/lib/python3.10/site-packages/mesa/time.py", line 123, in _wrapped_step
    self.model._advance_time()
  File "/home/os/.local/lib/python3.10/site-packages/mesa/model.py", line 122, in _advance_time
    self._steps += 1
AttributeError: 'Auction' object has no attribute '_steps'. Did you mean: 'step'?`

**Comment by M1kuW1ll** [comment]
Try a lower version of python (3.8 or 3.9) and a lower version of Mesa (before 2.0.0).

**Comment by hyue0768** [comment]
thanks, my problem is solved!
